#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiForFOL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="test1")]
	public partial class FOLDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertFOL_Input_1_1(FOL_Input_1_1 instance);
    partial void UpdateFOL_Input_1_1(FOL_Input_1_1 instance);
    partial void DeleteFOL_Input_1_1(FOL_Input_1_1 instance);
    partial void InsertFOL_Input_2_1(FOL_Input_2_1 instance);
    partial void UpdateFOL_Input_2_1(FOL_Input_2_1 instance);
    partial void DeleteFOL_Input_2_1(FOL_Input_2_1 instance);
    partial void InsertFOL_Input_3_1(FOL_Input_3_1 instance);
    partial void UpdateFOL_Input_3_1(FOL_Input_3_1 instance);
    partial void DeleteFOL_Input_3_1(FOL_Input_3_1 instance);
    #endregion
		
		public FOLDataClassesDataContext() : 
				base(global::ApiForFOL.Properties.Settings.Default.test1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FOLDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FOLDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FOLDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FOLDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<FOL_Input_1_1> FOL_Input_1_1
		{
			get
			{
				return this.GetTable<FOL_Input_1_1>();
			}
		}
		
		public System.Data.Linq.Table<FOL_Input_2_1> FOL_Input_2_1
		{
			get
			{
				return this.GetTable<FOL_Input_2_1>();
			}
		}
		
		public System.Data.Linq.Table<FOL_Input_3_1> FOL_Input_3_1
		{
			get
			{
				return this.GetTable<FOL_Input_3_1>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FOL_Input_1_1")]
	public partial class FOL_Input_1_1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _GLBPCCode;
		
		private string _GLBPCDescription;
		
		private string _GLOutputCode;
		
		private string _CustomerBPCCode;
		
		private string _DIM1;
		
		private string _Order;
		
		private string _CustomerOutputCode;
		
		private string _BU;
		
		private string _Segment;
		
		private System.Nullable<double> _Period1;
		
		private System.Nullable<double> _Period2;
		
		private System.Nullable<double> _Period3;
		
		private System.Nullable<double> _Period4;
		
		private System.Nullable<double> _Period5;
		
		private System.Nullable<double> _Period6;
		
		private System.Nullable<double> _Period7;
		
		private System.Nullable<double> _Period8;
		
		private System.Nullable<double> _Period9;
		
		private System.Nullable<double> _Period10;
		
		private System.Nullable<double> _Period11;
		
		private System.Nullable<double> _Period12;
		
		private System.Nullable<double> _Period13;
		
		private System.Nullable<double> _Period14;
		
		private System.Nullable<double> _Period15;
		
		private System.Nullable<double> _Period16;
		
		private System.Nullable<double> _Totals;
		
		private string _Type;
		
		private string _Version;
		
		private System.Nullable<System.DateTime> _InsertDate;
		
		private string _InsertUser;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnGLBPCCodeChanging(string value);
    partial void OnGLBPCCodeChanged();
    partial void OnGLBPCDescriptionChanging(string value);
    partial void OnGLBPCDescriptionChanged();
    partial void OnGLOutputCodeChanging(string value);
    partial void OnGLOutputCodeChanged();
    partial void OnCustomerBPCCodeChanging(string value);
    partial void OnCustomerBPCCodeChanged();
    partial void OnDIM1Changing(string value);
    partial void OnDIM1Changed();
    partial void OnOrderChanging(string value);
    partial void OnOrderChanged();
    partial void OnCustomerOutputCodeChanging(string value);
    partial void OnCustomerOutputCodeChanged();
    partial void OnBUChanging(string value);
    partial void OnBUChanged();
    partial void OnSegmentChanging(string value);
    partial void OnSegmentChanged();
    partial void OnPeriod1Changing(System.Nullable<double> value);
    partial void OnPeriod1Changed();
    partial void OnPeriod2Changing(System.Nullable<double> value);
    partial void OnPeriod2Changed();
    partial void OnPeriod3Changing(System.Nullable<double> value);
    partial void OnPeriod3Changed();
    partial void OnPeriod4Changing(System.Nullable<double> value);
    partial void OnPeriod4Changed();
    partial void OnPeriod5Changing(System.Nullable<double> value);
    partial void OnPeriod5Changed();
    partial void OnPeriod6Changing(System.Nullable<double> value);
    partial void OnPeriod6Changed();
    partial void OnPeriod7Changing(System.Nullable<double> value);
    partial void OnPeriod7Changed();
    partial void OnPeriod8Changing(System.Nullable<double> value);
    partial void OnPeriod8Changed();
    partial void OnPeriod9Changing(System.Nullable<double> value);
    partial void OnPeriod9Changed();
    partial void OnPeriod10Changing(System.Nullable<double> value);
    partial void OnPeriod10Changed();
    partial void OnPeriod11Changing(System.Nullable<double> value);
    partial void OnPeriod11Changed();
    partial void OnPeriod12Changing(System.Nullable<double> value);
    partial void OnPeriod12Changed();
    partial void OnPeriod13Changing(System.Nullable<double> value);
    partial void OnPeriod13Changed();
    partial void OnPeriod14Changing(System.Nullable<double> value);
    partial void OnPeriod14Changed();
    partial void OnPeriod15Changing(System.Nullable<double> value);
    partial void OnPeriod15Changed();
    partial void OnPeriod16Changing(System.Nullable<double> value);
    partial void OnPeriod16Changed();
    partial void OnTotalsChanging(System.Nullable<double> value);
    partial void OnTotalsChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnVersionChanging(string value);
    partial void OnVersionChanged();
    partial void OnInsertDateChanging(System.Nullable<System.DateTime> value);
    partial void OnInsertDateChanged();
    partial void OnInsertUserChanging(string value);
    partial void OnInsertUserChanged();
    #endregion
		
		public FOL_Input_1_1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GLBPCCode", DbType="VarChar(500)")]
		public string GLBPCCode
		{
			get
			{
				return this._GLBPCCode;
			}
			set
			{
				if ((this._GLBPCCode != value))
				{
					this.OnGLBPCCodeChanging(value);
					this.SendPropertyChanging();
					this._GLBPCCode = value;
					this.SendPropertyChanged("GLBPCCode");
					this.OnGLBPCCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GLBPCDescription", DbType="VarChar(500)")]
		public string GLBPCDescription
		{
			get
			{
				return this._GLBPCDescription;
			}
			set
			{
				if ((this._GLBPCDescription != value))
				{
					this.OnGLBPCDescriptionChanging(value);
					this.SendPropertyChanging();
					this._GLBPCDescription = value;
					this.SendPropertyChanged("GLBPCDescription");
					this.OnGLBPCDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GLOutputCode", DbType="VarChar(500)")]
		public string GLOutputCode
		{
			get
			{
				return this._GLOutputCode;
			}
			set
			{
				if ((this._GLOutputCode != value))
				{
					this.OnGLOutputCodeChanging(value);
					this.SendPropertyChanging();
					this._GLOutputCode = value;
					this.SendPropertyChanged("GLOutputCode");
					this.OnGLOutputCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerBPCCode", DbType="VarChar(500)")]
		public string CustomerBPCCode
		{
			get
			{
				return this._CustomerBPCCode;
			}
			set
			{
				if ((this._CustomerBPCCode != value))
				{
					this.OnCustomerBPCCodeChanging(value);
					this.SendPropertyChanging();
					this._CustomerBPCCode = value;
					this.SendPropertyChanged("CustomerBPCCode");
					this.OnCustomerBPCCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIM1", DbType="VarChar(500)")]
		public string DIM1
		{
			get
			{
				return this._DIM1;
			}
			set
			{
				if ((this._DIM1 != value))
				{
					this.OnDIM1Changing(value);
					this.SendPropertyChanging();
					this._DIM1 = value;
					this.SendPropertyChanged("DIM1");
					this.OnDIM1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Order]", Storage="_Order", DbType="VarChar(50)")]
		public string Order
		{
			get
			{
				return this._Order;
			}
			set
			{
				if ((this._Order != value))
				{
					this.OnOrderChanging(value);
					this.SendPropertyChanging();
					this._Order = value;
					this.SendPropertyChanged("Order");
					this.OnOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerOutputCode", DbType="VarChar(500)")]
		public string CustomerOutputCode
		{
			get
			{
				return this._CustomerOutputCode;
			}
			set
			{
				if ((this._CustomerOutputCode != value))
				{
					this.OnCustomerOutputCodeChanging(value);
					this.SendPropertyChanging();
					this._CustomerOutputCode = value;
					this.SendPropertyChanged("CustomerOutputCode");
					this.OnCustomerOutputCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BU", DbType="VarChar(50)")]
		public string BU
		{
			get
			{
				return this._BU;
			}
			set
			{
				if ((this._BU != value))
				{
					this.OnBUChanging(value);
					this.SendPropertyChanging();
					this._BU = value;
					this.SendPropertyChanged("BU");
					this.OnBUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment", DbType="VarChar(50)")]
		public string Segment
		{
			get
			{
				return this._Segment;
			}
			set
			{
				if ((this._Segment != value))
				{
					this.OnSegmentChanging(value);
					this.SendPropertyChanging();
					this._Segment = value;
					this.SendPropertyChanged("Segment");
					this.OnSegmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period1", DbType="Float")]
		public System.Nullable<double> Period1
		{
			get
			{
				return this._Period1;
			}
			set
			{
				if ((this._Period1 != value))
				{
					this.OnPeriod1Changing(value);
					this.SendPropertyChanging();
					this._Period1 = value;
					this.SendPropertyChanged("Period1");
					this.OnPeriod1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period2", DbType="Float")]
		public System.Nullable<double> Period2
		{
			get
			{
				return this._Period2;
			}
			set
			{
				if ((this._Period2 != value))
				{
					this.OnPeriod2Changing(value);
					this.SendPropertyChanging();
					this._Period2 = value;
					this.SendPropertyChanged("Period2");
					this.OnPeriod2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period3", DbType="Float")]
		public System.Nullable<double> Period3
		{
			get
			{
				return this._Period3;
			}
			set
			{
				if ((this._Period3 != value))
				{
					this.OnPeriod3Changing(value);
					this.SendPropertyChanging();
					this._Period3 = value;
					this.SendPropertyChanged("Period3");
					this.OnPeriod3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period4", DbType="Float")]
		public System.Nullable<double> Period4
		{
			get
			{
				return this._Period4;
			}
			set
			{
				if ((this._Period4 != value))
				{
					this.OnPeriod4Changing(value);
					this.SendPropertyChanging();
					this._Period4 = value;
					this.SendPropertyChanged("Period4");
					this.OnPeriod4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period5", DbType="Float")]
		public System.Nullable<double> Period5
		{
			get
			{
				return this._Period5;
			}
			set
			{
				if ((this._Period5 != value))
				{
					this.OnPeriod5Changing(value);
					this.SendPropertyChanging();
					this._Period5 = value;
					this.SendPropertyChanged("Period5");
					this.OnPeriod5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period6", DbType="Float")]
		public System.Nullable<double> Period6
		{
			get
			{
				return this._Period6;
			}
			set
			{
				if ((this._Period6 != value))
				{
					this.OnPeriod6Changing(value);
					this.SendPropertyChanging();
					this._Period6 = value;
					this.SendPropertyChanged("Period6");
					this.OnPeriod6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period7", DbType="Float")]
		public System.Nullable<double> Period7
		{
			get
			{
				return this._Period7;
			}
			set
			{
				if ((this._Period7 != value))
				{
					this.OnPeriod7Changing(value);
					this.SendPropertyChanging();
					this._Period7 = value;
					this.SendPropertyChanged("Period7");
					this.OnPeriod7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period8", DbType="Float")]
		public System.Nullable<double> Period8
		{
			get
			{
				return this._Period8;
			}
			set
			{
				if ((this._Period8 != value))
				{
					this.OnPeriod8Changing(value);
					this.SendPropertyChanging();
					this._Period8 = value;
					this.SendPropertyChanged("Period8");
					this.OnPeriod8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period9", DbType="Float")]
		public System.Nullable<double> Period9
		{
			get
			{
				return this._Period9;
			}
			set
			{
				if ((this._Period9 != value))
				{
					this.OnPeriod9Changing(value);
					this.SendPropertyChanging();
					this._Period9 = value;
					this.SendPropertyChanged("Period9");
					this.OnPeriod9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period10", DbType="Float")]
		public System.Nullable<double> Period10
		{
			get
			{
				return this._Period10;
			}
			set
			{
				if ((this._Period10 != value))
				{
					this.OnPeriod10Changing(value);
					this.SendPropertyChanging();
					this._Period10 = value;
					this.SendPropertyChanged("Period10");
					this.OnPeriod10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period11", DbType="Float")]
		public System.Nullable<double> Period11
		{
			get
			{
				return this._Period11;
			}
			set
			{
				if ((this._Period11 != value))
				{
					this.OnPeriod11Changing(value);
					this.SendPropertyChanging();
					this._Period11 = value;
					this.SendPropertyChanged("Period11");
					this.OnPeriod11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period12", DbType="Float")]
		public System.Nullable<double> Period12
		{
			get
			{
				return this._Period12;
			}
			set
			{
				if ((this._Period12 != value))
				{
					this.OnPeriod12Changing(value);
					this.SendPropertyChanging();
					this._Period12 = value;
					this.SendPropertyChanged("Period12");
					this.OnPeriod12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period13", DbType="Float")]
		public System.Nullable<double> Period13
		{
			get
			{
				return this._Period13;
			}
			set
			{
				if ((this._Period13 != value))
				{
					this.OnPeriod13Changing(value);
					this.SendPropertyChanging();
					this._Period13 = value;
					this.SendPropertyChanged("Period13");
					this.OnPeriod13Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period14", DbType="Float")]
		public System.Nullable<double> Period14
		{
			get
			{
				return this._Period14;
			}
			set
			{
				if ((this._Period14 != value))
				{
					this.OnPeriod14Changing(value);
					this.SendPropertyChanging();
					this._Period14 = value;
					this.SendPropertyChanged("Period14");
					this.OnPeriod14Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period15", DbType="Float")]
		public System.Nullable<double> Period15
		{
			get
			{
				return this._Period15;
			}
			set
			{
				if ((this._Period15 != value))
				{
					this.OnPeriod15Changing(value);
					this.SendPropertyChanging();
					this._Period15 = value;
					this.SendPropertyChanged("Period15");
					this.OnPeriod15Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period16", DbType="Float")]
		public System.Nullable<double> Period16
		{
			get
			{
				return this._Period16;
			}
			set
			{
				if ((this._Period16 != value))
				{
					this.OnPeriod16Changing(value);
					this.SendPropertyChanging();
					this._Period16 = value;
					this.SendPropertyChanged("Period16");
					this.OnPeriod16Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Totals", DbType="Float")]
		public System.Nullable<double> Totals
		{
			get
			{
				return this._Totals;
			}
			set
			{
				if ((this._Totals != value))
				{
					this.OnTotalsChanging(value);
					this.SendPropertyChanging();
					this._Totals = value;
					this.SendPropertyChanged("Totals");
					this.OnTotalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(50)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="VarChar(50)")]
		public string Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> InsertDate
		{
			get
			{
				return this._InsertDate;
			}
			set
			{
				if ((this._InsertDate != value))
				{
					this.OnInsertDateChanging(value);
					this.SendPropertyChanging();
					this._InsertDate = value;
					this.SendPropertyChanged("InsertDate");
					this.OnInsertDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertUser", DbType="VarChar(50)")]
		public string InsertUser
		{
			get
			{
				return this._InsertUser;
			}
			set
			{
				if ((this._InsertUser != value))
				{
					this.OnInsertUserChanging(value);
					this.SendPropertyChanging();
					this._InsertUser = value;
					this.SendPropertyChanged("InsertUser");
					this.OnInsertUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FOL_Input_2_1")]
	public partial class FOL_Input_2_1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _GLBPCCode;
		
		private string _GLBPCDescription;
		
		private string _GLOutputCode;
		
		private string _CustomerBPCCode;
		
		private string _DIM1;
		
		private string _Order;
		
		private string _CustomerOutputCode;
		
		private string _BU;
		
		private string _Segment;
		
		private System.Nullable<double> _Period1_Percent;
		
		private System.Nullable<double> _Period2_Percent;
		
		private System.Nullable<double> _Period3_Percent;
		
		private System.Nullable<double> _Period4_Percent;
		
		private System.Nullable<double> _Period5_Percent;
		
		private System.Nullable<double> _Period6_Percent;
		
		private System.Nullable<double> _Period7_Percent;
		
		private System.Nullable<double> _Period8_Percent;
		
		private System.Nullable<double> _Period9_Percent;
		
		private System.Nullable<double> _Period10_Percent;
		
		private System.Nullable<double> _Period11_Percent;
		
		private System.Nullable<double> _Period12_Percent;
		
		private System.Nullable<double> _Period13_Percent;
		
		private System.Nullable<double> _Period14_Percent;
		
		private System.Nullable<double> _Period15_Percent;
		
		private System.Nullable<double> _Period16_Percent;
		
		private string _Type;
		
		private string _Version;
		
		private System.Nullable<System.DateTime> _InsertDate;
		
		private string _InsertUser;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnGLBPCCodeChanging(string value);
    partial void OnGLBPCCodeChanged();
    partial void OnGLBPCDescriptionChanging(string value);
    partial void OnGLBPCDescriptionChanged();
    partial void OnGLOutputCodeChanging(string value);
    partial void OnGLOutputCodeChanged();
    partial void OnCustomerBPCCodeChanging(string value);
    partial void OnCustomerBPCCodeChanged();
    partial void OnDIM1Changing(string value);
    partial void OnDIM1Changed();
    partial void OnOrderChanging(string value);
    partial void OnOrderChanged();
    partial void OnCustomerOutputCodeChanging(string value);
    partial void OnCustomerOutputCodeChanged();
    partial void OnBUChanging(string value);
    partial void OnBUChanged();
    partial void OnSegmentChanging(string value);
    partial void OnSegmentChanged();
    partial void OnPeriod1_PercentChanging(System.Nullable<double> value);
    partial void OnPeriod1_PercentChanged();
    partial void OnPeriod2_PercentChanging(System.Nullable<double> value);
    partial void OnPeriod2_PercentChanged();
    partial void OnPeriod3_PercentChanging(System.Nullable<double> value);
    partial void OnPeriod3_PercentChanged();
    partial void OnPeriod4_PercentChanging(System.Nullable<double> value);
    partial void OnPeriod4_PercentChanged();
    partial void OnPeriod5_PercentChanging(System.Nullable<double> value);
    partial void OnPeriod5_PercentChanged();
    partial void OnPeriod6_PercentChanging(System.Nullable<double> value);
    partial void OnPeriod6_PercentChanged();
    partial void OnPeriod7_PercentChanging(System.Nullable<double> value);
    partial void OnPeriod7_PercentChanged();
    partial void OnPeriod8_PercentChanging(System.Nullable<double> value);
    partial void OnPeriod8_PercentChanged();
    partial void OnPeriod9_PercentChanging(System.Nullable<double> value);
    partial void OnPeriod9_PercentChanged();
    partial void OnPeriod10_PercentChanging(System.Nullable<double> value);
    partial void OnPeriod10_PercentChanged();
    partial void OnPeriod11_PercentChanging(System.Nullable<double> value);
    partial void OnPeriod11_PercentChanged();
    partial void OnPeriod12_PercentChanging(System.Nullable<double> value);
    partial void OnPeriod12_PercentChanged();
    partial void OnPeriod13_PercentChanging(System.Nullable<double> value);
    partial void OnPeriod13_PercentChanged();
    partial void OnPeriod14_PercentChanging(System.Nullable<double> value);
    partial void OnPeriod14_PercentChanged();
    partial void OnPeriod15_PercentChanging(System.Nullable<double> value);
    partial void OnPeriod15_PercentChanged();
    partial void OnPeriod16_PercentChanging(System.Nullable<double> value);
    partial void OnPeriod16_PercentChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnVersionChanging(string value);
    partial void OnVersionChanged();
    partial void OnInsertDateChanging(System.Nullable<System.DateTime> value);
    partial void OnInsertDateChanged();
    partial void OnInsertUserChanging(string value);
    partial void OnInsertUserChanged();
    #endregion
		
		public FOL_Input_2_1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GLBPCCode", DbType="VarChar(500)")]
		public string GLBPCCode
		{
			get
			{
				return this._GLBPCCode;
			}
			set
			{
				if ((this._GLBPCCode != value))
				{
					this.OnGLBPCCodeChanging(value);
					this.SendPropertyChanging();
					this._GLBPCCode = value;
					this.SendPropertyChanged("GLBPCCode");
					this.OnGLBPCCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GLBPCDescription", DbType="VarChar(500)")]
		public string GLBPCDescription
		{
			get
			{
				return this._GLBPCDescription;
			}
			set
			{
				if ((this._GLBPCDescription != value))
				{
					this.OnGLBPCDescriptionChanging(value);
					this.SendPropertyChanging();
					this._GLBPCDescription = value;
					this.SendPropertyChanged("GLBPCDescription");
					this.OnGLBPCDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GLOutputCode", DbType="VarChar(500)")]
		public string GLOutputCode
		{
			get
			{
				return this._GLOutputCode;
			}
			set
			{
				if ((this._GLOutputCode != value))
				{
					this.OnGLOutputCodeChanging(value);
					this.SendPropertyChanging();
					this._GLOutputCode = value;
					this.SendPropertyChanged("GLOutputCode");
					this.OnGLOutputCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerBPCCode", DbType="VarChar(500)")]
		public string CustomerBPCCode
		{
			get
			{
				return this._CustomerBPCCode;
			}
			set
			{
				if ((this._CustomerBPCCode != value))
				{
					this.OnCustomerBPCCodeChanging(value);
					this.SendPropertyChanging();
					this._CustomerBPCCode = value;
					this.SendPropertyChanged("CustomerBPCCode");
					this.OnCustomerBPCCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIM1", DbType="VarChar(50)")]
		public string DIM1
		{
			get
			{
				return this._DIM1;
			}
			set
			{
				if ((this._DIM1 != value))
				{
					this.OnDIM1Changing(value);
					this.SendPropertyChanging();
					this._DIM1 = value;
					this.SendPropertyChanged("DIM1");
					this.OnDIM1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Order]", Storage="_Order", DbType="VarChar(50)")]
		public string Order
		{
			get
			{
				return this._Order;
			}
			set
			{
				if ((this._Order != value))
				{
					this.OnOrderChanging(value);
					this.SendPropertyChanging();
					this._Order = value;
					this.SendPropertyChanged("Order");
					this.OnOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerOutputCode", DbType="VarChar(500)")]
		public string CustomerOutputCode
		{
			get
			{
				return this._CustomerOutputCode;
			}
			set
			{
				if ((this._CustomerOutputCode != value))
				{
					this.OnCustomerOutputCodeChanging(value);
					this.SendPropertyChanging();
					this._CustomerOutputCode = value;
					this.SendPropertyChanged("CustomerOutputCode");
					this.OnCustomerOutputCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BU", DbType="VarChar(50)")]
		public string BU
		{
			get
			{
				return this._BU;
			}
			set
			{
				if ((this._BU != value))
				{
					this.OnBUChanging(value);
					this.SendPropertyChanging();
					this._BU = value;
					this.SendPropertyChanged("BU");
					this.OnBUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment", DbType="VarChar(50)")]
		public string Segment
		{
			get
			{
				return this._Segment;
			}
			set
			{
				if ((this._Segment != value))
				{
					this.OnSegmentChanging(value);
					this.SendPropertyChanging();
					this._Segment = value;
					this.SendPropertyChanged("Segment");
					this.OnSegmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period1_Percent", DbType="Float")]
		public System.Nullable<double> Period1_Percent
		{
			get
			{
				return this._Period1_Percent;
			}
			set
			{
				if ((this._Period1_Percent != value))
				{
					this.OnPeriod1_PercentChanging(value);
					this.SendPropertyChanging();
					this._Period1_Percent = value;
					this.SendPropertyChanged("Period1_Percent");
					this.OnPeriod1_PercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period2_Percent", DbType="Float")]
		public System.Nullable<double> Period2_Percent
		{
			get
			{
				return this._Period2_Percent;
			}
			set
			{
				if ((this._Period2_Percent != value))
				{
					this.OnPeriod2_PercentChanging(value);
					this.SendPropertyChanging();
					this._Period2_Percent = value;
					this.SendPropertyChanged("Period2_Percent");
					this.OnPeriod2_PercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period3_Percent", DbType="Float")]
		public System.Nullable<double> Period3_Percent
		{
			get
			{
				return this._Period3_Percent;
			}
			set
			{
				if ((this._Period3_Percent != value))
				{
					this.OnPeriod3_PercentChanging(value);
					this.SendPropertyChanging();
					this._Period3_Percent = value;
					this.SendPropertyChanged("Period3_Percent");
					this.OnPeriod3_PercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period4_Percent", DbType="Float")]
		public System.Nullable<double> Period4_Percent
		{
			get
			{
				return this._Period4_Percent;
			}
			set
			{
				if ((this._Period4_Percent != value))
				{
					this.OnPeriod4_PercentChanging(value);
					this.SendPropertyChanging();
					this._Period4_Percent = value;
					this.SendPropertyChanged("Period4_Percent");
					this.OnPeriod4_PercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period5_Percent", DbType="Float")]
		public System.Nullable<double> Period5_Percent
		{
			get
			{
				return this._Period5_Percent;
			}
			set
			{
				if ((this._Period5_Percent != value))
				{
					this.OnPeriod5_PercentChanging(value);
					this.SendPropertyChanging();
					this._Period5_Percent = value;
					this.SendPropertyChanged("Period5_Percent");
					this.OnPeriod5_PercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period6_Percent", DbType="Float")]
		public System.Nullable<double> Period6_Percent
		{
			get
			{
				return this._Period6_Percent;
			}
			set
			{
				if ((this._Period6_Percent != value))
				{
					this.OnPeriod6_PercentChanging(value);
					this.SendPropertyChanging();
					this._Period6_Percent = value;
					this.SendPropertyChanged("Period6_Percent");
					this.OnPeriod6_PercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period7_Percent", DbType="Float")]
		public System.Nullable<double> Period7_Percent
		{
			get
			{
				return this._Period7_Percent;
			}
			set
			{
				if ((this._Period7_Percent != value))
				{
					this.OnPeriod7_PercentChanging(value);
					this.SendPropertyChanging();
					this._Period7_Percent = value;
					this.SendPropertyChanged("Period7_Percent");
					this.OnPeriod7_PercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period8_Percent", DbType="Float")]
		public System.Nullable<double> Period8_Percent
		{
			get
			{
				return this._Period8_Percent;
			}
			set
			{
				if ((this._Period8_Percent != value))
				{
					this.OnPeriod8_PercentChanging(value);
					this.SendPropertyChanging();
					this._Period8_Percent = value;
					this.SendPropertyChanged("Period8_Percent");
					this.OnPeriod8_PercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period9_Percent", DbType="Float")]
		public System.Nullable<double> Period9_Percent
		{
			get
			{
				return this._Period9_Percent;
			}
			set
			{
				if ((this._Period9_Percent != value))
				{
					this.OnPeriod9_PercentChanging(value);
					this.SendPropertyChanging();
					this._Period9_Percent = value;
					this.SendPropertyChanged("Period9_Percent");
					this.OnPeriod9_PercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period10_Percent", DbType="Float")]
		public System.Nullable<double> Period10_Percent
		{
			get
			{
				return this._Period10_Percent;
			}
			set
			{
				if ((this._Period10_Percent != value))
				{
					this.OnPeriod10_PercentChanging(value);
					this.SendPropertyChanging();
					this._Period10_Percent = value;
					this.SendPropertyChanged("Period10_Percent");
					this.OnPeriod10_PercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period11_Percent", DbType="Float")]
		public System.Nullable<double> Period11_Percent
		{
			get
			{
				return this._Period11_Percent;
			}
			set
			{
				if ((this._Period11_Percent != value))
				{
					this.OnPeriod11_PercentChanging(value);
					this.SendPropertyChanging();
					this._Period11_Percent = value;
					this.SendPropertyChanged("Period11_Percent");
					this.OnPeriod11_PercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period12_Percent", DbType="Float")]
		public System.Nullable<double> Period12_Percent
		{
			get
			{
				return this._Period12_Percent;
			}
			set
			{
				if ((this._Period12_Percent != value))
				{
					this.OnPeriod12_PercentChanging(value);
					this.SendPropertyChanging();
					this._Period12_Percent = value;
					this.SendPropertyChanged("Period12_Percent");
					this.OnPeriod12_PercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period13_Percent", DbType="Float")]
		public System.Nullable<double> Period13_Percent
		{
			get
			{
				return this._Period13_Percent;
			}
			set
			{
				if ((this._Period13_Percent != value))
				{
					this.OnPeriod13_PercentChanging(value);
					this.SendPropertyChanging();
					this._Period13_Percent = value;
					this.SendPropertyChanged("Period13_Percent");
					this.OnPeriod13_PercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period14_Percent", DbType="Float")]
		public System.Nullable<double> Period14_Percent
		{
			get
			{
				return this._Period14_Percent;
			}
			set
			{
				if ((this._Period14_Percent != value))
				{
					this.OnPeriod14_PercentChanging(value);
					this.SendPropertyChanging();
					this._Period14_Percent = value;
					this.SendPropertyChanged("Period14_Percent");
					this.OnPeriod14_PercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period15_Percent", DbType="Float")]
		public System.Nullable<double> Period15_Percent
		{
			get
			{
				return this._Period15_Percent;
			}
			set
			{
				if ((this._Period15_Percent != value))
				{
					this.OnPeriod15_PercentChanging(value);
					this.SendPropertyChanging();
					this._Period15_Percent = value;
					this.SendPropertyChanged("Period15_Percent");
					this.OnPeriod15_PercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period16_Percent", DbType="Float")]
		public System.Nullable<double> Period16_Percent
		{
			get
			{
				return this._Period16_Percent;
			}
			set
			{
				if ((this._Period16_Percent != value))
				{
					this.OnPeriod16_PercentChanging(value);
					this.SendPropertyChanging();
					this._Period16_Percent = value;
					this.SendPropertyChanged("Period16_Percent");
					this.OnPeriod16_PercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="VarChar(50)")]
		public string Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> InsertDate
		{
			get
			{
				return this._InsertDate;
			}
			set
			{
				if ((this._InsertDate != value))
				{
					this.OnInsertDateChanging(value);
					this.SendPropertyChanging();
					this._InsertDate = value;
					this.SendPropertyChanged("InsertDate");
					this.OnInsertDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertUser", DbType="VarChar(50)")]
		public string InsertUser
		{
			get
			{
				return this._InsertUser;
			}
			set
			{
				if ((this._InsertUser != value))
				{
					this.OnInsertUserChanging(value);
					this.SendPropertyChanging();
					this._InsertUser = value;
					this.SendPropertyChanged("InsertUser");
					this.OnInsertUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FOL_Input_3_1")]
	public partial class FOL_Input_3_1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _GLBPCCode;
		
		private string _GLBPCDescription;
		
		private string _GLOutputCode;
		
		private string _CustomerBPCCode;
		
		private string _DIM1;
		
		private string _Order;
		
		private string _CustomerOutputCode;
		
		private string _BU;
		
		private string _Segment;
		
		private System.Nullable<double> _Period1_Amount;
		
		private System.Nullable<double> _Period2_Amount;
		
		private System.Nullable<double> _Period3_Amount;
		
		private System.Nullable<double> _Period4_Amount;
		
		private System.Nullable<double> _Period5_Amount;
		
		private System.Nullable<double> _Period6_Amount;
		
		private System.Nullable<double> _Period7_Amount;
		
		private System.Nullable<double> _Period8_Amount;
		
		private System.Nullable<double> _Period9_Amount;
		
		private System.Nullable<double> _Period10_Amount;
		
		private System.Nullable<double> _Period11_Amount;
		
		private System.Nullable<double> _Period12_Amount;
		
		private System.Nullable<double> _Period13_Amount;
		
		private System.Nullable<double> _Period14_Amount;
		
		private System.Nullable<double> _Period15_Amount;
		
		private System.Nullable<double> _Period16_Amount;
		
		private string _Type;
		
		private string _Version;
		
		private System.Nullable<System.DateTime> _InsertDate;
		
		private string _InsertUser;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnGLBPCCodeChanging(string value);
    partial void OnGLBPCCodeChanged();
    partial void OnGLBPCDescriptionChanging(string value);
    partial void OnGLBPCDescriptionChanged();
    partial void OnGLOutputCodeChanging(string value);
    partial void OnGLOutputCodeChanged();
    partial void OnCustomerBPCCodeChanging(string value);
    partial void OnCustomerBPCCodeChanged();
    partial void OnDIM1Changing(string value);
    partial void OnDIM1Changed();
    partial void OnOrderChanging(string value);
    partial void OnOrderChanged();
    partial void OnCustomerOutputCodeChanging(string value);
    partial void OnCustomerOutputCodeChanged();
    partial void OnBUChanging(string value);
    partial void OnBUChanged();
    partial void OnSegmentChanging(string value);
    partial void OnSegmentChanged();
    partial void OnPeriod1_AmountChanging(System.Nullable<double> value);
    partial void OnPeriod1_AmountChanged();
    partial void OnPeriod2_AmountChanging(System.Nullable<double> value);
    partial void OnPeriod2_AmountChanged();
    partial void OnPeriod3_AmountChanging(System.Nullable<double> value);
    partial void OnPeriod3_AmountChanged();
    partial void OnPeriod4_AmountChanging(System.Nullable<double> value);
    partial void OnPeriod4_AmountChanged();
    partial void OnPeriod5_AmountChanging(System.Nullable<double> value);
    partial void OnPeriod5_AmountChanged();
    partial void OnPeriod6_AmountChanging(System.Nullable<double> value);
    partial void OnPeriod6_AmountChanged();
    partial void OnPeriod7_AmountChanging(System.Nullable<double> value);
    partial void OnPeriod7_AmountChanged();
    partial void OnPeriod8_AmountChanging(System.Nullable<double> value);
    partial void OnPeriod8_AmountChanged();
    partial void OnPeriod9_AmountChanging(System.Nullable<double> value);
    partial void OnPeriod9_AmountChanged();
    partial void OnPeriod10_AmountChanging(System.Nullable<double> value);
    partial void OnPeriod10_AmountChanged();
    partial void OnPeriod11_AmountChanging(System.Nullable<double> value);
    partial void OnPeriod11_AmountChanged();
    partial void OnPeriod12_AmountChanging(System.Nullable<double> value);
    partial void OnPeriod12_AmountChanged();
    partial void OnPeriod13_AmountChanging(System.Nullable<double> value);
    partial void OnPeriod13_AmountChanged();
    partial void OnPeriod14_AmountChanging(System.Nullable<double> value);
    partial void OnPeriod14_AmountChanged();
    partial void OnPeriod15_AmountChanging(System.Nullable<double> value);
    partial void OnPeriod15_AmountChanged();
    partial void OnPeriod16_AmountChanging(System.Nullable<double> value);
    partial void OnPeriod16_AmountChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnVersionChanging(string value);
    partial void OnVersionChanged();
    partial void OnInsertDateChanging(System.Nullable<System.DateTime> value);
    partial void OnInsertDateChanged();
    partial void OnInsertUserChanging(string value);
    partial void OnInsertUserChanged();
    #endregion
		
		public FOL_Input_3_1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GLBPCCode", DbType="VarChar(500)")]
		public string GLBPCCode
		{
			get
			{
				return this._GLBPCCode;
			}
			set
			{
				if ((this._GLBPCCode != value))
				{
					this.OnGLBPCCodeChanging(value);
					this.SendPropertyChanging();
					this._GLBPCCode = value;
					this.SendPropertyChanged("GLBPCCode");
					this.OnGLBPCCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GLBPCDescription", DbType="VarChar(MAX)")]
		public string GLBPCDescription
		{
			get
			{
				return this._GLBPCDescription;
			}
			set
			{
				if ((this._GLBPCDescription != value))
				{
					this.OnGLBPCDescriptionChanging(value);
					this.SendPropertyChanging();
					this._GLBPCDescription = value;
					this.SendPropertyChanged("GLBPCDescription");
					this.OnGLBPCDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GLOutputCode", DbType="VarChar(500)")]
		public string GLOutputCode
		{
			get
			{
				return this._GLOutputCode;
			}
			set
			{
				if ((this._GLOutputCode != value))
				{
					this.OnGLOutputCodeChanging(value);
					this.SendPropertyChanging();
					this._GLOutputCode = value;
					this.SendPropertyChanged("GLOutputCode");
					this.OnGLOutputCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerBPCCode", DbType="VarChar(500)")]
		public string CustomerBPCCode
		{
			get
			{
				return this._CustomerBPCCode;
			}
			set
			{
				if ((this._CustomerBPCCode != value))
				{
					this.OnCustomerBPCCodeChanging(value);
					this.SendPropertyChanging();
					this._CustomerBPCCode = value;
					this.SendPropertyChanged("CustomerBPCCode");
					this.OnCustomerBPCCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIM1", DbType="VarChar(50)")]
		public string DIM1
		{
			get
			{
				return this._DIM1;
			}
			set
			{
				if ((this._DIM1 != value))
				{
					this.OnDIM1Changing(value);
					this.SendPropertyChanging();
					this._DIM1 = value;
					this.SendPropertyChanged("DIM1");
					this.OnDIM1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Order]", Storage="_Order", DbType="VarChar(50)")]
		public string Order
		{
			get
			{
				return this._Order;
			}
			set
			{
				if ((this._Order != value))
				{
					this.OnOrderChanging(value);
					this.SendPropertyChanging();
					this._Order = value;
					this.SendPropertyChanged("Order");
					this.OnOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerOutputCode", DbType="VarChar(500)")]
		public string CustomerOutputCode
		{
			get
			{
				return this._CustomerOutputCode;
			}
			set
			{
				if ((this._CustomerOutputCode != value))
				{
					this.OnCustomerOutputCodeChanging(value);
					this.SendPropertyChanging();
					this._CustomerOutputCode = value;
					this.SendPropertyChanged("CustomerOutputCode");
					this.OnCustomerOutputCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BU", DbType="VarChar(50)")]
		public string BU
		{
			get
			{
				return this._BU;
			}
			set
			{
				if ((this._BU != value))
				{
					this.OnBUChanging(value);
					this.SendPropertyChanging();
					this._BU = value;
					this.SendPropertyChanged("BU");
					this.OnBUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment", DbType="VarChar(50)")]
		public string Segment
		{
			get
			{
				return this._Segment;
			}
			set
			{
				if ((this._Segment != value))
				{
					this.OnSegmentChanging(value);
					this.SendPropertyChanging();
					this._Segment = value;
					this.SendPropertyChanged("Segment");
					this.OnSegmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period1_Amount", DbType="Float")]
		public System.Nullable<double> Period1_Amount
		{
			get
			{
				return this._Period1_Amount;
			}
			set
			{
				if ((this._Period1_Amount != value))
				{
					this.OnPeriod1_AmountChanging(value);
					this.SendPropertyChanging();
					this._Period1_Amount = value;
					this.SendPropertyChanged("Period1_Amount");
					this.OnPeriod1_AmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period2_Amount", DbType="Float")]
		public System.Nullable<double> Period2_Amount
		{
			get
			{
				return this._Period2_Amount;
			}
			set
			{
				if ((this._Period2_Amount != value))
				{
					this.OnPeriod2_AmountChanging(value);
					this.SendPropertyChanging();
					this._Period2_Amount = value;
					this.SendPropertyChanged("Period2_Amount");
					this.OnPeriod2_AmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period3_Amount", DbType="Float")]
		public System.Nullable<double> Period3_Amount
		{
			get
			{
				return this._Period3_Amount;
			}
			set
			{
				if ((this._Period3_Amount != value))
				{
					this.OnPeriod3_AmountChanging(value);
					this.SendPropertyChanging();
					this._Period3_Amount = value;
					this.SendPropertyChanged("Period3_Amount");
					this.OnPeriod3_AmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period4_Amount", DbType="Float")]
		public System.Nullable<double> Period4_Amount
		{
			get
			{
				return this._Period4_Amount;
			}
			set
			{
				if ((this._Period4_Amount != value))
				{
					this.OnPeriod4_AmountChanging(value);
					this.SendPropertyChanging();
					this._Period4_Amount = value;
					this.SendPropertyChanged("Period4_Amount");
					this.OnPeriod4_AmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period5_Amount", DbType="Float")]
		public System.Nullable<double> Period5_Amount
		{
			get
			{
				return this._Period5_Amount;
			}
			set
			{
				if ((this._Period5_Amount != value))
				{
					this.OnPeriod5_AmountChanging(value);
					this.SendPropertyChanging();
					this._Period5_Amount = value;
					this.SendPropertyChanged("Period5_Amount");
					this.OnPeriod5_AmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period6_Amount", DbType="Float")]
		public System.Nullable<double> Period6_Amount
		{
			get
			{
				return this._Period6_Amount;
			}
			set
			{
				if ((this._Period6_Amount != value))
				{
					this.OnPeriod6_AmountChanging(value);
					this.SendPropertyChanging();
					this._Period6_Amount = value;
					this.SendPropertyChanged("Period6_Amount");
					this.OnPeriod6_AmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period7_Amount", DbType="Float")]
		public System.Nullable<double> Period7_Amount
		{
			get
			{
				return this._Period7_Amount;
			}
			set
			{
				if ((this._Period7_Amount != value))
				{
					this.OnPeriod7_AmountChanging(value);
					this.SendPropertyChanging();
					this._Period7_Amount = value;
					this.SendPropertyChanged("Period7_Amount");
					this.OnPeriod7_AmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period8_Amount", DbType="Float")]
		public System.Nullable<double> Period8_Amount
		{
			get
			{
				return this._Period8_Amount;
			}
			set
			{
				if ((this._Period8_Amount != value))
				{
					this.OnPeriod8_AmountChanging(value);
					this.SendPropertyChanging();
					this._Period8_Amount = value;
					this.SendPropertyChanged("Period8_Amount");
					this.OnPeriod8_AmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period9_Amount", DbType="Float")]
		public System.Nullable<double> Period9_Amount
		{
			get
			{
				return this._Period9_Amount;
			}
			set
			{
				if ((this._Period9_Amount != value))
				{
					this.OnPeriod9_AmountChanging(value);
					this.SendPropertyChanging();
					this._Period9_Amount = value;
					this.SendPropertyChanged("Period9_Amount");
					this.OnPeriod9_AmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period10_Amount", DbType="Float")]
		public System.Nullable<double> Period10_Amount
		{
			get
			{
				return this._Period10_Amount;
			}
			set
			{
				if ((this._Period10_Amount != value))
				{
					this.OnPeriod10_AmountChanging(value);
					this.SendPropertyChanging();
					this._Period10_Amount = value;
					this.SendPropertyChanged("Period10_Amount");
					this.OnPeriod10_AmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period11_Amount", DbType="Float")]
		public System.Nullable<double> Period11_Amount
		{
			get
			{
				return this._Period11_Amount;
			}
			set
			{
				if ((this._Period11_Amount != value))
				{
					this.OnPeriod11_AmountChanging(value);
					this.SendPropertyChanging();
					this._Period11_Amount = value;
					this.SendPropertyChanged("Period11_Amount");
					this.OnPeriod11_AmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period12_Amount", DbType="Float")]
		public System.Nullable<double> Period12_Amount
		{
			get
			{
				return this._Period12_Amount;
			}
			set
			{
				if ((this._Period12_Amount != value))
				{
					this.OnPeriod12_AmountChanging(value);
					this.SendPropertyChanging();
					this._Period12_Amount = value;
					this.SendPropertyChanged("Period12_Amount");
					this.OnPeriod12_AmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period13_Amount", DbType="Float")]
		public System.Nullable<double> Period13_Amount
		{
			get
			{
				return this._Period13_Amount;
			}
			set
			{
				if ((this._Period13_Amount != value))
				{
					this.OnPeriod13_AmountChanging(value);
					this.SendPropertyChanging();
					this._Period13_Amount = value;
					this.SendPropertyChanged("Period13_Amount");
					this.OnPeriod13_AmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period14_Amount", DbType="Float")]
		public System.Nullable<double> Period14_Amount
		{
			get
			{
				return this._Period14_Amount;
			}
			set
			{
				if ((this._Period14_Amount != value))
				{
					this.OnPeriod14_AmountChanging(value);
					this.SendPropertyChanging();
					this._Period14_Amount = value;
					this.SendPropertyChanged("Period14_Amount");
					this.OnPeriod14_AmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period15_Amount", DbType="Float")]
		public System.Nullable<double> Period15_Amount
		{
			get
			{
				return this._Period15_Amount;
			}
			set
			{
				if ((this._Period15_Amount != value))
				{
					this.OnPeriod15_AmountChanging(value);
					this.SendPropertyChanging();
					this._Period15_Amount = value;
					this.SendPropertyChanged("Period15_Amount");
					this.OnPeriod15_AmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period16_Amount", DbType="Float")]
		public System.Nullable<double> Period16_Amount
		{
			get
			{
				return this._Period16_Amount;
			}
			set
			{
				if ((this._Period16_Amount != value))
				{
					this.OnPeriod16_AmountChanging(value);
					this.SendPropertyChanging();
					this._Period16_Amount = value;
					this.SendPropertyChanged("Period16_Amount");
					this.OnPeriod16_AmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="VarChar(50)")]
		public string Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> InsertDate
		{
			get
			{
				return this._InsertDate;
			}
			set
			{
				if ((this._InsertDate != value))
				{
					this.OnInsertDateChanging(value);
					this.SendPropertyChanging();
					this._InsertDate = value;
					this.SendPropertyChanged("InsertDate");
					this.OnInsertDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertUser", DbType="VarChar(50)")]
		public string InsertUser
		{
			get
			{
				return this._InsertUser;
			}
			set
			{
				if ((this._InsertUser != value))
				{
					this.OnInsertUserChanging(value);
					this.SendPropertyChanging();
					this._InsertUser = value;
					this.SendPropertyChanged("InsertUser");
					this.OnInsertUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
