#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiForRackManage.DataContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PNINOUT")]
	public partial class RackDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertRack_copy(Rack_copy instance);
    partial void UpdateRack_copy(Rack_copy instance);
    partial void DeleteRack_copy(Rack_copy instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertRack(Rack instance);
    partial void UpdateRack(Rack instance);
    partial void DeleteRack(Rack instance);
    partial void InsertInstrument(Instrument instance);
    partial void UpdateInstrument(Instrument instance);
    partial void DeleteInstrument(Instrument instance);
    partial void InsertJ750(J750 instance);
    partial void UpdateJ750(J750 instance);
    partial void DeleteJ750(J750 instance);
    partial void InsertJ750_Board(J750_Board instance);
    partial void UpdateJ750_Board(J750_Board instance);
    partial void DeleteJ750_Board(J750_Board instance);
    #endregion
		
		public RackDataContext() : 
				base(global::ApiForRackManage.Properties.Settings.Default.PNINOUTConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RackDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RackDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RackDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RackDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Rack_copy> Rack_copy
		{
			get
			{
				return this.GetTable<Rack_copy>();
			}
		}
		
		public System.Data.Linq.Table<User> User
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Rack> Rack
		{
			get
			{
				return this.GetTable<Rack>();
			}
		}
		
		public System.Data.Linq.Table<Instrument> Instrument
		{
			get
			{
				return this.GetTable<Instrument>();
			}
		}
		
		public System.Data.Linq.Table<J750> J750
		{
			get
			{
				return this.GetTable<J750>();
			}
		}
		
		public System.Data.Linq.Table<J750_Board> J750_Board
		{
			get
			{
				return this.GetTable<J750_Board>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rack_copy")]
	public partial class Rack_copy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _PN;
		
		private string _RackName;
		
		private System.Nullable<int> _ActualQTY;
		
		private System.Nullable<int> _Size;
		
		private string _SNView;
		
		private string _TimeView;
		
		private string _SlotView;
		
		private string _Command;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPNChanging(string value);
    partial void OnPNChanged();
    partial void OnRackNameChanging(string value);
    partial void OnRackNameChanged();
    partial void OnActualQTYChanging(System.Nullable<int> value);
    partial void OnActualQTYChanged();
    partial void OnSizeChanging(System.Nullable<int> value);
    partial void OnSizeChanged();
    partial void OnSNViewChanging(string value);
    partial void OnSNViewChanged();
    partial void OnTimeViewChanging(string value);
    partial void OnTimeViewChanged();
    partial void OnSlotViewChanging(string value);
    partial void OnSlotViewChanged();
    partial void OnCommandChanging(string value);
    partial void OnCommandChanged();
    #endregion
		
		public Rack_copy()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PN", DbType="NVarChar(50)")]
		public string PN
		{
			get
			{
				return this._PN;
			}
			set
			{
				if ((this._PN != value))
				{
					this.OnPNChanging(value);
					this.SendPropertyChanging();
					this._PN = value;
					this.SendPropertyChanged("PN");
					this.OnPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RackName", DbType="NVarChar(50)")]
		public string RackName
		{
			get
			{
				return this._RackName;
			}
			set
			{
				if ((this._RackName != value))
				{
					this.OnRackNameChanging(value);
					this.SendPropertyChanging();
					this._RackName = value;
					this.SendPropertyChanged("RackName");
					this.OnRackNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActualQTY", DbType="Int")]
		public System.Nullable<int> ActualQTY
		{
			get
			{
				return this._ActualQTY;
			}
			set
			{
				if ((this._ActualQTY != value))
				{
					this.OnActualQTYChanging(value);
					this.SendPropertyChanging();
					this._ActualQTY = value;
					this.SendPropertyChanged("ActualQTY");
					this.OnActualQTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="Int")]
		public System.Nullable<int> Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this.OnSizeChanging(value);
					this.SendPropertyChanging();
					this._Size = value;
					this.SendPropertyChanged("Size");
					this.OnSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNView", DbType="NVarChar(555)")]
		public string SNView
		{
			get
			{
				return this._SNView;
			}
			set
			{
				if ((this._SNView != value))
				{
					this.OnSNViewChanging(value);
					this.SendPropertyChanging();
					this._SNView = value;
					this.SendPropertyChanged("SNView");
					this.OnSNViewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeView", DbType="NVarChar(MAX)")]
		public string TimeView
		{
			get
			{
				return this._TimeView;
			}
			set
			{
				if ((this._TimeView != value))
				{
					this.OnTimeViewChanging(value);
					this.SendPropertyChanging();
					this._TimeView = value;
					this.SendPropertyChanged("TimeView");
					this.OnTimeViewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SlotView", DbType="NVarChar(555)")]
		public string SlotView
		{
			get
			{
				return this._SlotView;
			}
			set
			{
				if ((this._SlotView != value))
				{
					this.OnSlotViewChanging(value);
					this.SendPropertyChanging();
					this._SlotView = value;
					this.SendPropertyChanged("SlotView");
					this.OnSlotViewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Command", DbType="NVarChar(555)")]
		public string Command
		{
			get
			{
				return this._Command;
			}
			set
			{
				if ((this._Command != value))
				{
					this.OnCommandChanging(value);
					this.SendPropertyChanging();
					this._Command = value;
					this.SendPropertyChanged("Command");
					this.OnCommandChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private string _PW;
		
		private int _LV;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPWChanging(string value);
    partial void OnPWChanged();
    partial void OnLVChanging(int value);
    partial void OnLVChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PW", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PW
		{
			get
			{
				return this._PW;
			}
			set
			{
				if ((this._PW != value))
				{
					this.OnPWChanging(value);
					this.SendPropertyChanging();
					this._PW = value;
					this.SendPropertyChanged("PW");
					this.OnPWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LV", DbType="Int NOT NULL")]
		public int LV
		{
			get
			{
				return this._LV;
			}
			set
			{
				if ((this._LV != value))
				{
					this.OnLVChanging(value);
					this.SendPropertyChanging();
					this._LV = value;
					this.SendPropertyChanged("LV");
					this.OnLVChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rack")]
	public partial class Rack : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _PN;
		
		private string _RackName;
		
		private System.Nullable<int> _ActualQTY;
		
		private System.Nullable<int> _Size;
		
		private string _SNView;
		
		private string _TimeView;
		
		private string _SlotView;
		
		private string _Command;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPNChanging(string value);
    partial void OnPNChanged();
    partial void OnRackNameChanging(string value);
    partial void OnRackNameChanged();
    partial void OnActualQTYChanging(System.Nullable<int> value);
    partial void OnActualQTYChanged();
    partial void OnSizeChanging(System.Nullable<int> value);
    partial void OnSizeChanged();
    partial void OnSNViewChanging(string value);
    partial void OnSNViewChanged();
    partial void OnTimeViewChanging(string value);
    partial void OnTimeViewChanged();
    partial void OnSlotViewChanging(string value);
    partial void OnSlotViewChanged();
    partial void OnCommandChanging(string value);
    partial void OnCommandChanged();
    #endregion
		
		public Rack()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PN", DbType="NVarChar(50)")]
		public string PN
		{
			get
			{
				return this._PN;
			}
			set
			{
				if ((this._PN != value))
				{
					this.OnPNChanging(value);
					this.SendPropertyChanging();
					this._PN = value;
					this.SendPropertyChanged("PN");
					this.OnPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RackName", DbType="NVarChar(50)")]
		public string RackName
		{
			get
			{
				return this._RackName;
			}
			set
			{
				if ((this._RackName != value))
				{
					this.OnRackNameChanging(value);
					this.SendPropertyChanging();
					this._RackName = value;
					this.SendPropertyChanged("RackName");
					this.OnRackNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActualQTY", DbType="Int")]
		public System.Nullable<int> ActualQTY
		{
			get
			{
				return this._ActualQTY;
			}
			set
			{
				if ((this._ActualQTY != value))
				{
					this.OnActualQTYChanging(value);
					this.SendPropertyChanging();
					this._ActualQTY = value;
					this.SendPropertyChanged("ActualQTY");
					this.OnActualQTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="Int")]
		public System.Nullable<int> Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this.OnSizeChanging(value);
					this.SendPropertyChanging();
					this._Size = value;
					this.SendPropertyChanged("Size");
					this.OnSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNView", DbType="NVarChar(555)")]
		public string SNView
		{
			get
			{
				return this._SNView;
			}
			set
			{
				if ((this._SNView != value))
				{
					this.OnSNViewChanging(value);
					this.SendPropertyChanging();
					this._SNView = value;
					this.SendPropertyChanged("SNView");
					this.OnSNViewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeView", DbType="NVarChar(MAX)")]
		public string TimeView
		{
			get
			{
				return this._TimeView;
			}
			set
			{
				if ((this._TimeView != value))
				{
					this.OnTimeViewChanging(value);
					this.SendPropertyChanging();
					this._TimeView = value;
					this.SendPropertyChanged("TimeView");
					this.OnTimeViewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SlotView", DbType="NVarChar(555)")]
		public string SlotView
		{
			get
			{
				return this._SlotView;
			}
			set
			{
				if ((this._SlotView != value))
				{
					this.OnSlotViewChanging(value);
					this.SendPropertyChanging();
					this._SlotView = value;
					this.SendPropertyChanged("SlotView");
					this.OnSlotViewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Command", DbType="NVarChar(555)")]
		public string Command
		{
			get
			{
				return this._Command;
			}
			set
			{
				if ((this._Command != value))
				{
					this.OnCommandChanging(value);
					this.SendPropertyChanging();
					this._Command = value;
					this.SendPropertyChanged("Command");
					this.OnCommandChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Instrument")]
	public partial class Instrument : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PN;
		
		private string _DES;
		
		private string _MFR;
		
		private string _OTC;
		
		private System.Nullable<int> _DAY;
		
		private System.Nullable<int> _R;
		
		private System.Nullable<int> _Y;
		
		private System.Nullable<int> _G;
		
		private System.Nullable<int> _ARQ;
		
		private System.Nullable<int> _QTY;
		
		private string _TYPE;
		
		private int _ID;
		
		private System.Nullable<int> _BI;
		
		private string _Remark;
		
		private string _RemarkBy;
		
		private System.Nullable<bool> _SendMail;
		
		private System.Nullable<int> _MOQ;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPNChanging(string value);
    partial void OnPNChanged();
    partial void OnDESChanging(string value);
    partial void OnDESChanged();
    partial void OnMFRChanging(string value);
    partial void OnMFRChanged();
    partial void OnOTCChanging(string value);
    partial void OnOTCChanged();
    partial void OnDAYChanging(System.Nullable<int> value);
    partial void OnDAYChanged();
    partial void OnRChanging(System.Nullable<int> value);
    partial void OnRChanged();
    partial void OnYChanging(System.Nullable<int> value);
    partial void OnYChanged();
    partial void OnGChanging(System.Nullable<int> value);
    partial void OnGChanged();
    partial void OnARQChanging(System.Nullable<int> value);
    partial void OnARQChanged();
    partial void OnQTYChanging(System.Nullable<int> value);
    partial void OnQTYChanged();
    partial void OnTYPEChanging(string value);
    partial void OnTYPEChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBIChanging(System.Nullable<int> value);
    partial void OnBIChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    partial void OnRemarkByChanging(string value);
    partial void OnRemarkByChanged();
    partial void OnSendMailChanging(System.Nullable<bool> value);
    partial void OnSendMailChanged();
    partial void OnMOQChanging(System.Nullable<int> value);
    partial void OnMOQChanged();
    #endregion
		
		public Instrument()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PN", DbType="NVarChar(50)")]
		public string PN
		{
			get
			{
				return this._PN;
			}
			set
			{
				if ((this._PN != value))
				{
					this.OnPNChanging(value);
					this.SendPropertyChanging();
					this._PN = value;
					this.SendPropertyChanged("PN");
					this.OnPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DES", DbType="NVarChar(200)")]
		public string DES
		{
			get
			{
				return this._DES;
			}
			set
			{
				if ((this._DES != value))
				{
					this.OnDESChanging(value);
					this.SendPropertyChanging();
					this._DES = value;
					this.SendPropertyChanged("DES");
					this.OnDESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MFR", DbType="NVarChar(200)")]
		public string MFR
		{
			get
			{
				return this._MFR;
			}
			set
			{
				if ((this._MFR != value))
				{
					this.OnMFRChanging(value);
					this.SendPropertyChanging();
					this._MFR = value;
					this.SendPropertyChanged("MFR");
					this.OnMFRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OTC", DbType="NVarChar(200)")]
		public string OTC
		{
			get
			{
				return this._OTC;
			}
			set
			{
				if ((this._OTC != value))
				{
					this.OnOTCChanging(value);
					this.SendPropertyChanging();
					this._OTC = value;
					this.SendPropertyChanged("OTC");
					this.OnOTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAY", DbType="Int")]
		public System.Nullable<int> DAY
		{
			get
			{
				return this._DAY;
			}
			set
			{
				if ((this._DAY != value))
				{
					this.OnDAYChanging(value);
					this.SendPropertyChanging();
					this._DAY = value;
					this.SendPropertyChanged("DAY");
					this.OnDAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R", DbType="Int")]
		public System.Nullable<int> R
		{
			get
			{
				return this._R;
			}
			set
			{
				if ((this._R != value))
				{
					this.OnRChanging(value);
					this.SendPropertyChanging();
					this._R = value;
					this.SendPropertyChanged("R");
					this.OnRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y", DbType="Int")]
		public System.Nullable<int> Y
		{
			get
			{
				return this._Y;
			}
			set
			{
				if ((this._Y != value))
				{
					this.OnYChanging(value);
					this.SendPropertyChanging();
					this._Y = value;
					this.SendPropertyChanged("Y");
					this.OnYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G", DbType="Int")]
		public System.Nullable<int> G
		{
			get
			{
				return this._G;
			}
			set
			{
				if ((this._G != value))
				{
					this.OnGChanging(value);
					this.SendPropertyChanging();
					this._G = value;
					this.SendPropertyChanged("G");
					this.OnGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARQ", DbType="Int")]
		public System.Nullable<int> ARQ
		{
			get
			{
				return this._ARQ;
			}
			set
			{
				if ((this._ARQ != value))
				{
					this.OnARQChanging(value);
					this.SendPropertyChanging();
					this._ARQ = value;
					this.SendPropertyChanged("ARQ");
					this.OnARQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY", DbType="Int")]
		public System.Nullable<int> QTY
		{
			get
			{
				return this._QTY;
			}
			set
			{
				if ((this._QTY != value))
				{
					this.OnQTYChanging(value);
					this.SendPropertyChanging();
					this._QTY = value;
					this.SendPropertyChanged("QTY");
					this.OnQTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="NVarChar(50)")]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this.OnTYPEChanging(value);
					this.SendPropertyChanging();
					this._TYPE = value;
					this.SendPropertyChanged("TYPE");
					this.OnTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BI", DbType="Int")]
		public System.Nullable<int> BI
		{
			get
			{
				return this._BI;
			}
			set
			{
				if ((this._BI != value))
				{
					this.OnBIChanging(value);
					this.SendPropertyChanging();
					this._BI = value;
					this.SendPropertyChanged("BI");
					this.OnBIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemarkBy", DbType="NVarChar(50)")]
		public string RemarkBy
		{
			get
			{
				return this._RemarkBy;
			}
			set
			{
				if ((this._RemarkBy != value))
				{
					this.OnRemarkByChanging(value);
					this.SendPropertyChanging();
					this._RemarkBy = value;
					this.SendPropertyChanged("RemarkBy");
					this.OnRemarkByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendMail", DbType="Bit")]
		public System.Nullable<bool> SendMail
		{
			get
			{
				return this._SendMail;
			}
			set
			{
				if ((this._SendMail != value))
				{
					this.OnSendMailChanging(value);
					this.SendPropertyChanging();
					this._SendMail = value;
					this.SendPropertyChanged("SendMail");
					this.OnSendMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOQ", DbType="Int")]
		public System.Nullable<int> MOQ
		{
			get
			{
				return this._MOQ;
			}
			set
			{
				if ((this._MOQ != value))
				{
					this.OnMOQChanging(value);
					this.SendPropertyChanging();
					this._MOQ = value;
					this.SendPropertyChanged("MOQ");
					this.OnMOQChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.J750")]
	public partial class J750 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PN;
		
		private string _DES;
		
		private string _MFR;
		
		private string _OTC;
		
		private System.Nullable<int> _DAY;
		
		private System.Nullable<int> _ARQ;
		
		private System.Nullable<int> _QTY;
		
		private int _ID;
		
		private System.Nullable<int> _BI;
		
		private string _Remark;
		
		private string _RemarkBy;
		
		private System.Nullable<bool> _SendMail;
		
		private System.Nullable<int> _MOQ;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPNChanging(string value);
    partial void OnPNChanged();
    partial void OnDESChanging(string value);
    partial void OnDESChanged();
    partial void OnMFRChanging(string value);
    partial void OnMFRChanged();
    partial void OnOTCChanging(string value);
    partial void OnOTCChanged();
    partial void OnDAYChanging(System.Nullable<int> value);
    partial void OnDAYChanged();
    partial void OnARQChanging(System.Nullable<int> value);
    partial void OnARQChanged();
    partial void OnQTYChanging(System.Nullable<int> value);
    partial void OnQTYChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBIChanging(System.Nullable<int> value);
    partial void OnBIChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    partial void OnRemarkByChanging(string value);
    partial void OnRemarkByChanged();
    partial void OnSendMailChanging(System.Nullable<bool> value);
    partial void OnSendMailChanged();
    partial void OnMOQChanging(System.Nullable<int> value);
    partial void OnMOQChanged();
    #endregion
		
		public J750()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PN", DbType="NVarChar(50)")]
		public string PN
		{
			get
			{
				return this._PN;
			}
			set
			{
				if ((this._PN != value))
				{
					this.OnPNChanging(value);
					this.SendPropertyChanging();
					this._PN = value;
					this.SendPropertyChanged("PN");
					this.OnPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DES", DbType="NVarChar(200)")]
		public string DES
		{
			get
			{
				return this._DES;
			}
			set
			{
				if ((this._DES != value))
				{
					this.OnDESChanging(value);
					this.SendPropertyChanging();
					this._DES = value;
					this.SendPropertyChanged("DES");
					this.OnDESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MFR", DbType="NVarChar(200)")]
		public string MFR
		{
			get
			{
				return this._MFR;
			}
			set
			{
				if ((this._MFR != value))
				{
					this.OnMFRChanging(value);
					this.SendPropertyChanging();
					this._MFR = value;
					this.SendPropertyChanged("MFR");
					this.OnMFRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OTC", DbType="NVarChar(200)")]
		public string OTC
		{
			get
			{
				return this._OTC;
			}
			set
			{
				if ((this._OTC != value))
				{
					this.OnOTCChanging(value);
					this.SendPropertyChanging();
					this._OTC = value;
					this.SendPropertyChanged("OTC");
					this.OnOTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAY", DbType="Int")]
		public System.Nullable<int> DAY
		{
			get
			{
				return this._DAY;
			}
			set
			{
				if ((this._DAY != value))
				{
					this.OnDAYChanging(value);
					this.SendPropertyChanging();
					this._DAY = value;
					this.SendPropertyChanged("DAY");
					this.OnDAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARQ", DbType="Int")]
		public System.Nullable<int> ARQ
		{
			get
			{
				return this._ARQ;
			}
			set
			{
				if ((this._ARQ != value))
				{
					this.OnARQChanging(value);
					this.SendPropertyChanging();
					this._ARQ = value;
					this.SendPropertyChanged("ARQ");
					this.OnARQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY", DbType="Int")]
		public System.Nullable<int> QTY
		{
			get
			{
				return this._QTY;
			}
			set
			{
				if ((this._QTY != value))
				{
					this.OnQTYChanging(value);
					this.SendPropertyChanging();
					this._QTY = value;
					this.SendPropertyChanged("QTY");
					this.OnQTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BI", DbType="Int")]
		public System.Nullable<int> BI
		{
			get
			{
				return this._BI;
			}
			set
			{
				if ((this._BI != value))
				{
					this.OnBIChanging(value);
					this.SendPropertyChanging();
					this._BI = value;
					this.SendPropertyChanged("BI");
					this.OnBIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemarkBy", DbType="NVarChar(50)")]
		public string RemarkBy
		{
			get
			{
				return this._RemarkBy;
			}
			set
			{
				if ((this._RemarkBy != value))
				{
					this.OnRemarkByChanging(value);
					this.SendPropertyChanging();
					this._RemarkBy = value;
					this.SendPropertyChanged("RemarkBy");
					this.OnRemarkByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendMail", DbType="Bit")]
		public System.Nullable<bool> SendMail
		{
			get
			{
				return this._SendMail;
			}
			set
			{
				if ((this._SendMail != value))
				{
					this.OnSendMailChanging(value);
					this.SendPropertyChanging();
					this._SendMail = value;
					this.SendPropertyChanged("SendMail");
					this.OnSendMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOQ", DbType="Int")]
		public System.Nullable<int> MOQ
		{
			get
			{
				return this._MOQ;
			}
			set
			{
				if ((this._MOQ != value))
				{
					this.OnMOQChanging(value);
					this.SendPropertyChanging();
					this._MOQ = value;
					this.SendPropertyChanged("MOQ");
					this.OnMOQChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.J750_Board")]
	public partial class J750_Board : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PN;
		
		private string _DES;
		
		private string _MFR;
		
		private string _OTC;
		
		private System.Nullable<int> _DAY;
		
		private System.Nullable<int> _ARQ;
		
		private System.Nullable<int> _QTY;
		
		private int _ID;
		
		private System.Nullable<int> _BI;
		
		private string _Remark;
		
		private string _RemarkBy;
		
		private System.Nullable<bool> _SendMail;
		
		private System.Nullable<int> _MOQ;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPNChanging(string value);
    partial void OnPNChanged();
    partial void OnDESChanging(string value);
    partial void OnDESChanged();
    partial void OnMFRChanging(string value);
    partial void OnMFRChanged();
    partial void OnOTCChanging(string value);
    partial void OnOTCChanged();
    partial void OnDAYChanging(System.Nullable<int> value);
    partial void OnDAYChanged();
    partial void OnARQChanging(System.Nullable<int> value);
    partial void OnARQChanged();
    partial void OnQTYChanging(System.Nullable<int> value);
    partial void OnQTYChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBIChanging(System.Nullable<int> value);
    partial void OnBIChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    partial void OnRemarkByChanging(string value);
    partial void OnRemarkByChanged();
    partial void OnSendMailChanging(System.Nullable<bool> value);
    partial void OnSendMailChanged();
    partial void OnMOQChanging(System.Nullable<int> value);
    partial void OnMOQChanged();
    #endregion
		
		public J750_Board()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PN", DbType="NVarChar(50)")]
		public string PN
		{
			get
			{
				return this._PN;
			}
			set
			{
				if ((this._PN != value))
				{
					this.OnPNChanging(value);
					this.SendPropertyChanging();
					this._PN = value;
					this.SendPropertyChanged("PN");
					this.OnPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DES", DbType="NVarChar(200)")]
		public string DES
		{
			get
			{
				return this._DES;
			}
			set
			{
				if ((this._DES != value))
				{
					this.OnDESChanging(value);
					this.SendPropertyChanging();
					this._DES = value;
					this.SendPropertyChanged("DES");
					this.OnDESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MFR", DbType="NVarChar(200)")]
		public string MFR
		{
			get
			{
				return this._MFR;
			}
			set
			{
				if ((this._MFR != value))
				{
					this.OnMFRChanging(value);
					this.SendPropertyChanging();
					this._MFR = value;
					this.SendPropertyChanged("MFR");
					this.OnMFRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OTC", DbType="NVarChar(200)")]
		public string OTC
		{
			get
			{
				return this._OTC;
			}
			set
			{
				if ((this._OTC != value))
				{
					this.OnOTCChanging(value);
					this.SendPropertyChanging();
					this._OTC = value;
					this.SendPropertyChanged("OTC");
					this.OnOTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAY", DbType="Int")]
		public System.Nullable<int> DAY
		{
			get
			{
				return this._DAY;
			}
			set
			{
				if ((this._DAY != value))
				{
					this.OnDAYChanging(value);
					this.SendPropertyChanging();
					this._DAY = value;
					this.SendPropertyChanged("DAY");
					this.OnDAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARQ", DbType="Int")]
		public System.Nullable<int> ARQ
		{
			get
			{
				return this._ARQ;
			}
			set
			{
				if ((this._ARQ != value))
				{
					this.OnARQChanging(value);
					this.SendPropertyChanging();
					this._ARQ = value;
					this.SendPropertyChanged("ARQ");
					this.OnARQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY", DbType="Int")]
		public System.Nullable<int> QTY
		{
			get
			{
				return this._QTY;
			}
			set
			{
				if ((this._QTY != value))
				{
					this.OnQTYChanging(value);
					this.SendPropertyChanging();
					this._QTY = value;
					this.SendPropertyChanged("QTY");
					this.OnQTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BI", DbType="Int")]
		public System.Nullable<int> BI
		{
			get
			{
				return this._BI;
			}
			set
			{
				if ((this._BI != value))
				{
					this.OnBIChanging(value);
					this.SendPropertyChanging();
					this._BI = value;
					this.SendPropertyChanged("BI");
					this.OnBIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemarkBy", DbType="NVarChar(50)")]
		public string RemarkBy
		{
			get
			{
				return this._RemarkBy;
			}
			set
			{
				if ((this._RemarkBy != value))
				{
					this.OnRemarkByChanging(value);
					this.SendPropertyChanging();
					this._RemarkBy = value;
					this.SendPropertyChanged("RemarkBy");
					this.OnRemarkByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendMail", DbType="Bit")]
		public System.Nullable<bool> SendMail
		{
			get
			{
				return this._SendMail;
			}
			set
			{
				if ((this._SendMail != value))
				{
					this.OnSendMailChanging(value);
					this.SendPropertyChanging();
					this._SendMail = value;
					this.SendPropertyChanged("SendMail");
					this.OnSendMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOQ", DbType="Int")]
		public System.Nullable<int> MOQ
		{
			get
			{
				return this._MOQ;
			}
			set
			{
				if ((this._MOQ != value))
				{
					this.OnMOQChanging(value);
					this.SendPropertyChanging();
					this._MOQ = value;
					this.SendPropertyChanged("MOQ");
					this.OnMOQChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
