#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiForMaterialKitting.DataContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SlotKB")]
	public partial class MaterialDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertSummaryH(SummaryH instance);
    partial void UpdateSummaryH(SummaryH instance);
    partial void DeleteSummaryH(SummaryH instance);
    #endregion
		
		public MaterialDataContext() : 
				base(global::ApiForMaterialKitting.Properties.Settings.Default.SlotKBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MaterialDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MaterialDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MaterialDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MaterialDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SummaryH> SummaryH
		{
			get
			{
				return this.GetTable<SummaryH>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SummaryH")]
	public partial class SummaryH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SystemSlot;
		
		private string _SystemModel;
		
		private string _Customer;
		
		private string _PO;
		
		private string _SO;
		
		private string _VSA;
		
		private string _ShipWeek;
		
		private string _ShipDate;
		
		private string _CORC;
		
		private string _Ship;
		
		private string _Pack;
		
		private string _ButtonUp;
		
		private string _QFAA;
		
		private string _CSW;
		
		private string _TestBU;
		
		private string _PV;
		
		private string _CoreBU;
		
		private string _OI;
		
		private string _Launch;
		
		private string _OpenIssue;
		
		private string _CloseIssue;
		
		private string _EngIssue;
		
		private string _Remark;
		
		private System.Nullable<System.DateTime> _ModifiedDate;
		
		private System.Nullable<bool> _IsMore;
		
		private System.Nullable<bool> _Lock;
		
		private string _Pin;
		
		private string _PSB;
		
		private string _SSB;
		
		private string _Utah;
		
		private string _DCPM;
		
		private string _PAC;
		
		private string _Action;
		
		private string _Owner;
		
		private string _DueDay;
		
		private string _OTD;
		
		private System.Nullable<bool> _NeedAction;
		
		private string _Crate;
		
		private System.Nullable<int> _InstallLevel;
		
		private string _Hex;
		
		private string _VHDVS;
		
		private string _Myone;
		
		private string _Mytwo;
		
		private string _Mythree;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSystemSlotChanging(string value);
    partial void OnSystemSlotChanged();
    partial void OnSystemModelChanging(string value);
    partial void OnSystemModelChanged();
    partial void OnCustomerChanging(string value);
    partial void OnCustomerChanged();
    partial void OnPOChanging(string value);
    partial void OnPOChanged();
    partial void OnSOChanging(string value);
    partial void OnSOChanged();
    partial void OnVSAChanging(string value);
    partial void OnVSAChanged();
    partial void OnShipWeekChanging(string value);
    partial void OnShipWeekChanged();
    partial void OnShipDateChanging(string value);
    partial void OnShipDateChanged();
    partial void OnCORCChanging(string value);
    partial void OnCORCChanged();
    partial void OnShipChanging(string value);
    partial void OnShipChanged();
    partial void OnPackChanging(string value);
    partial void OnPackChanged();
    partial void OnButtonUpChanging(string value);
    partial void OnButtonUpChanged();
    partial void OnQFAAChanging(string value);
    partial void OnQFAAChanged();
    partial void OnCSWChanging(string value);
    partial void OnCSWChanged();
    partial void OnTestBUChanging(string value);
    partial void OnTestBUChanged();
    partial void OnPVChanging(string value);
    partial void OnPVChanged();
    partial void OnCoreBUChanging(string value);
    partial void OnCoreBUChanged();
    partial void OnOIChanging(string value);
    partial void OnOIChanged();
    partial void OnLaunchChanging(string value);
    partial void OnLaunchChanged();
    partial void OnOpenIssueChanging(string value);
    partial void OnOpenIssueChanged();
    partial void OnCloseIssueChanging(string value);
    partial void OnCloseIssueChanged();
    partial void OnEngIssueChanging(string value);
    partial void OnEngIssueChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    partial void OnModifiedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateChanged();
    partial void OnIsMoreChanging(System.Nullable<bool> value);
    partial void OnIsMoreChanged();
    partial void OnLockChanging(System.Nullable<bool> value);
    partial void OnLockChanged();
    partial void OnPinChanging(string value);
    partial void OnPinChanged();
    partial void OnPSBChanging(string value);
    partial void OnPSBChanged();
    partial void OnSSBChanging(string value);
    partial void OnSSBChanged();
    partial void OnUtahChanging(string value);
    partial void OnUtahChanged();
    partial void OnDCPMChanging(string value);
    partial void OnDCPMChanged();
    partial void OnPACChanging(string value);
    partial void OnPACChanged();
    partial void OnActionChanging(string value);
    partial void OnActionChanged();
    partial void OnOwnerChanging(string value);
    partial void OnOwnerChanged();
    partial void OnDueDayChanging(string value);
    partial void OnDueDayChanged();
    partial void OnOTDChanging(string value);
    partial void OnOTDChanged();
    partial void OnNeedActionChanging(System.Nullable<bool> value);
    partial void OnNeedActionChanged();
    partial void OnCrateChanging(string value);
    partial void OnCrateChanged();
    partial void OnInstallLevelChanging(System.Nullable<int> value);
    partial void OnInstallLevelChanged();
    partial void OnHexChanging(string value);
    partial void OnHexChanged();
    partial void OnVHDVSChanging(string value);
    partial void OnVHDVSChanged();
    partial void OnMyoneChanging(string value);
    partial void OnMyoneChanged();
    partial void OnMytwoChanging(string value);
    partial void OnMytwoChanged();
    partial void OnMythreeChanging(string value);
    partial void OnMythreeChanged();
    #endregion
		
		public SummaryH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemSlot", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SystemSlot
		{
			get
			{
				return this._SystemSlot;
			}
			set
			{
				if ((this._SystemSlot != value))
				{
					this.OnSystemSlotChanging(value);
					this.SendPropertyChanging();
					this._SystemSlot = value;
					this.SendPropertyChanged("SystemSlot");
					this.OnSystemSlotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemModel", DbType="VarChar(50)")]
		public string SystemModel
		{
			get
			{
				return this._SystemModel;
			}
			set
			{
				if ((this._SystemModel != value))
				{
					this.OnSystemModelChanging(value);
					this.SendPropertyChanging();
					this._SystemModel = value;
					this.SendPropertyChanged("SystemModel");
					this.OnSystemModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer", DbType="VarChar(50)")]
		public string Customer
		{
			get
			{
				return this._Customer;
			}
			set
			{
				if ((this._Customer != value))
				{
					this.OnCustomerChanging(value);
					this.SendPropertyChanging();
					this._Customer = value;
					this.SendPropertyChanged("Customer");
					this.OnCustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PO", DbType="VarChar(50)")]
		public string PO
		{
			get
			{
				return this._PO;
			}
			set
			{
				if ((this._PO != value))
				{
					this.OnPOChanging(value);
					this.SendPropertyChanging();
					this._PO = value;
					this.SendPropertyChanged("PO");
					this.OnPOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO", DbType="VarChar(50)")]
		public string SO
		{
			get
			{
				return this._SO;
			}
			set
			{
				if ((this._SO != value))
				{
					this.OnSOChanging(value);
					this.SendPropertyChanging();
					this._SO = value;
					this.SendPropertyChanged("SO");
					this.OnSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VSA", DbType="VarChar(50)")]
		public string VSA
		{
			get
			{
				return this._VSA;
			}
			set
			{
				if ((this._VSA != value))
				{
					this.OnVSAChanging(value);
					this.SendPropertyChanging();
					this._VSA = value;
					this.SendPropertyChanged("VSA");
					this.OnVSAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipWeek", DbType="VarChar(50)")]
		public string ShipWeek
		{
			get
			{
				return this._ShipWeek;
			}
			set
			{
				if ((this._ShipWeek != value))
				{
					this.OnShipWeekChanging(value);
					this.SendPropertyChanging();
					this._ShipWeek = value;
					this.SendPropertyChanged("ShipWeek");
					this.OnShipWeekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipDate", DbType="VarChar(50)")]
		public string ShipDate
		{
			get
			{
				return this._ShipDate;
			}
			set
			{
				if ((this._ShipDate != value))
				{
					this.OnShipDateChanging(value);
					this.SendPropertyChanging();
					this._ShipDate = value;
					this.SendPropertyChanged("ShipDate");
					this.OnShipDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORC", DbType="VarChar(50)")]
		public string CORC
		{
			get
			{
				return this._CORC;
			}
			set
			{
				if ((this._CORC != value))
				{
					this.OnCORCChanging(value);
					this.SendPropertyChanging();
					this._CORC = value;
					this.SendPropertyChanged("CORC");
					this.OnCORCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ship", DbType="VarChar(50)")]
		public string Ship
		{
			get
			{
				return this._Ship;
			}
			set
			{
				if ((this._Ship != value))
				{
					this.OnShipChanging(value);
					this.SendPropertyChanging();
					this._Ship = value;
					this.SendPropertyChanged("Ship");
					this.OnShipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pack", DbType="VarChar(50)")]
		public string Pack
		{
			get
			{
				return this._Pack;
			}
			set
			{
				if ((this._Pack != value))
				{
					this.OnPackChanging(value);
					this.SendPropertyChanging();
					this._Pack = value;
					this.SendPropertyChanged("Pack");
					this.OnPackChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ButtonUp", DbType="VarChar(50)")]
		public string ButtonUp
		{
			get
			{
				return this._ButtonUp;
			}
			set
			{
				if ((this._ButtonUp != value))
				{
					this.OnButtonUpChanging(value);
					this.SendPropertyChanging();
					this._ButtonUp = value;
					this.SendPropertyChanged("ButtonUp");
					this.OnButtonUpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QFAA", DbType="VarChar(50)")]
		public string QFAA
		{
			get
			{
				return this._QFAA;
			}
			set
			{
				if ((this._QFAA != value))
				{
					this.OnQFAAChanging(value);
					this.SendPropertyChanging();
					this._QFAA = value;
					this.SendPropertyChanged("QFAA");
					this.OnQFAAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CSW", DbType="VarChar(50)")]
		public string CSW
		{
			get
			{
				return this._CSW;
			}
			set
			{
				if ((this._CSW != value))
				{
					this.OnCSWChanging(value);
					this.SendPropertyChanging();
					this._CSW = value;
					this.SendPropertyChanged("CSW");
					this.OnCSWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestBU", DbType="VarChar(50)")]
		public string TestBU
		{
			get
			{
				return this._TestBU;
			}
			set
			{
				if ((this._TestBU != value))
				{
					this.OnTestBUChanging(value);
					this.SendPropertyChanging();
					this._TestBU = value;
					this.SendPropertyChanged("TestBU");
					this.OnTestBUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PV", DbType="VarChar(50)")]
		public string PV
		{
			get
			{
				return this._PV;
			}
			set
			{
				if ((this._PV != value))
				{
					this.OnPVChanging(value);
					this.SendPropertyChanging();
					this._PV = value;
					this.SendPropertyChanged("PV");
					this.OnPVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoreBU", DbType="VarChar(50)")]
		public string CoreBU
		{
			get
			{
				return this._CoreBU;
			}
			set
			{
				if ((this._CoreBU != value))
				{
					this.OnCoreBUChanging(value);
					this.SendPropertyChanging();
					this._CoreBU = value;
					this.SendPropertyChanged("CoreBU");
					this.OnCoreBUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OI", DbType="VarChar(50)")]
		public string OI
		{
			get
			{
				return this._OI;
			}
			set
			{
				if ((this._OI != value))
				{
					this.OnOIChanging(value);
					this.SendPropertyChanging();
					this._OI = value;
					this.SendPropertyChanged("OI");
					this.OnOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Launch", DbType="VarChar(50)")]
		public string Launch
		{
			get
			{
				return this._Launch;
			}
			set
			{
				if ((this._Launch != value))
				{
					this.OnLaunchChanging(value);
					this.SendPropertyChanging();
					this._Launch = value;
					this.SendPropertyChanged("Launch");
					this.OnLaunchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpenIssue", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string OpenIssue
		{
			get
			{
				return this._OpenIssue;
			}
			set
			{
				if ((this._OpenIssue != value))
				{
					this.OnOpenIssueChanging(value);
					this.SendPropertyChanging();
					this._OpenIssue = value;
					this.SendPropertyChanged("OpenIssue");
					this.OnOpenIssueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CloseIssue", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string CloseIssue
		{
			get
			{
				return this._CloseIssue;
			}
			set
			{
				if ((this._CloseIssue != value))
				{
					this.OnCloseIssueChanging(value);
					this.SendPropertyChanging();
					this._CloseIssue = value;
					this.SendPropertyChanged("CloseIssue");
					this.OnCloseIssueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EngIssue", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string EngIssue
		{
			get
			{
				return this._EngIssue;
			}
			set
			{
				if ((this._EngIssue != value))
				{
					this.OnEngIssueChanging(value);
					this.SendPropertyChanging();
					this._EngIssue = value;
					this.SendPropertyChanged("EngIssue");
					this.OnEngIssueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this.OnModifiedDateChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDate = value;
					this.SendPropertyChanged("ModifiedDate");
					this.OnModifiedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMore", DbType="Bit")]
		public System.Nullable<bool> IsMore
		{
			get
			{
				return this._IsMore;
			}
			set
			{
				if ((this._IsMore != value))
				{
					this.OnIsMoreChanging(value);
					this.SendPropertyChanging();
					this._IsMore = value;
					this.SendPropertyChanged("IsMore");
					this.OnIsMoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lock", DbType="Bit")]
		public System.Nullable<bool> Lock
		{
			get
			{
				return this._Lock;
			}
			set
			{
				if ((this._Lock != value))
				{
					this.OnLockChanging(value);
					this.SendPropertyChanging();
					this._Lock = value;
					this.SendPropertyChanged("Lock");
					this.OnLockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pin", DbType="VarChar(50)")]
		public string Pin
		{
			get
			{
				return this._Pin;
			}
			set
			{
				if ((this._Pin != value))
				{
					this.OnPinChanging(value);
					this.SendPropertyChanging();
					this._Pin = value;
					this.SendPropertyChanged("Pin");
					this.OnPinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PSB", DbType="VarChar(50)")]
		public string PSB
		{
			get
			{
				return this._PSB;
			}
			set
			{
				if ((this._PSB != value))
				{
					this.OnPSBChanging(value);
					this.SendPropertyChanging();
					this._PSB = value;
					this.SendPropertyChanged("PSB");
					this.OnPSBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSB", DbType="VarChar(50)")]
		public string SSB
		{
			get
			{
				return this._SSB;
			}
			set
			{
				if ((this._SSB != value))
				{
					this.OnSSBChanging(value);
					this.SendPropertyChanging();
					this._SSB = value;
					this.SendPropertyChanged("SSB");
					this.OnSSBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Utah", DbType="VarChar(50)")]
		public string Utah
		{
			get
			{
				return this._Utah;
			}
			set
			{
				if ((this._Utah != value))
				{
					this.OnUtahChanging(value);
					this.SendPropertyChanging();
					this._Utah = value;
					this.SendPropertyChanged("Utah");
					this.OnUtahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCPM", DbType="VarChar(50)")]
		public string DCPM
		{
			get
			{
				return this._DCPM;
			}
			set
			{
				if ((this._DCPM != value))
				{
					this.OnDCPMChanging(value);
					this.SendPropertyChanging();
					this._DCPM = value;
					this.SendPropertyChanged("DCPM");
					this.OnDCPMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAC", DbType="VarChar(50)")]
		public string PAC
		{
			get
			{
				return this._PAC;
			}
			set
			{
				if ((this._PAC != value))
				{
					this.OnPACChanging(value);
					this.SendPropertyChanging();
					this._PAC = value;
					this.SendPropertyChanged("PAC");
					this.OnPACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Action", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Action
		{
			get
			{
				return this._Action;
			}
			set
			{
				if ((this._Action != value))
				{
					this.OnActionChanging(value);
					this.SendPropertyChanging();
					this._Action = value;
					this.SendPropertyChanged("Action");
					this.OnActionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Owner", DbType="VarChar(50)")]
		public string Owner
		{
			get
			{
				return this._Owner;
			}
			set
			{
				if ((this._Owner != value))
				{
					this.OnOwnerChanging(value);
					this.SendPropertyChanging();
					this._Owner = value;
					this.SendPropertyChanged("Owner");
					this.OnOwnerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DueDay", DbType="VarChar(50)")]
		public string DueDay
		{
			get
			{
				return this._DueDay;
			}
			set
			{
				if ((this._DueDay != value))
				{
					this.OnDueDayChanging(value);
					this.SendPropertyChanging();
					this._DueDay = value;
					this.SendPropertyChanged("DueDay");
					this.OnDueDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OTD", DbType="VarChar(50)")]
		public string OTD
		{
			get
			{
				return this._OTD;
			}
			set
			{
				if ((this._OTD != value))
				{
					this.OnOTDChanging(value);
					this.SendPropertyChanging();
					this._OTD = value;
					this.SendPropertyChanged("OTD");
					this.OnOTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NeedAction", DbType="Bit")]
		public System.Nullable<bool> NeedAction
		{
			get
			{
				return this._NeedAction;
			}
			set
			{
				if ((this._NeedAction != value))
				{
					this.OnNeedActionChanging(value);
					this.SendPropertyChanging();
					this._NeedAction = value;
					this.SendPropertyChanged("NeedAction");
					this.OnNeedActionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Crate", DbType="VarChar(50)")]
		public string Crate
		{
			get
			{
				return this._Crate;
			}
			set
			{
				if ((this._Crate != value))
				{
					this.OnCrateChanging(value);
					this.SendPropertyChanging();
					this._Crate = value;
					this.SendPropertyChanged("Crate");
					this.OnCrateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstallLevel", DbType="Int")]
		public System.Nullable<int> InstallLevel
		{
			get
			{
				return this._InstallLevel;
			}
			set
			{
				if ((this._InstallLevel != value))
				{
					this.OnInstallLevelChanging(value);
					this.SendPropertyChanging();
					this._InstallLevel = value;
					this.SendPropertyChanged("InstallLevel");
					this.OnInstallLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hex", DbType="VarChar(50)")]
		public string Hex
		{
			get
			{
				return this._Hex;
			}
			set
			{
				if ((this._Hex != value))
				{
					this.OnHexChanging(value);
					this.SendPropertyChanging();
					this._Hex = value;
					this.SendPropertyChanged("Hex");
					this.OnHexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VHDVS", DbType="VarChar(50)")]
		public string VHDVS
		{
			get
			{
				return this._VHDVS;
			}
			set
			{
				if ((this._VHDVS != value))
				{
					this.OnVHDVSChanging(value);
					this.SendPropertyChanging();
					this._VHDVS = value;
					this.SendPropertyChanged("VHDVS");
					this.OnVHDVSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Myone", DbType="VarChar(50)")]
		public string Myone
		{
			get
			{
				return this._Myone;
			}
			set
			{
				if ((this._Myone != value))
				{
					this.OnMyoneChanging(value);
					this.SendPropertyChanging();
					this._Myone = value;
					this.SendPropertyChanged("Myone");
					this.OnMyoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mytwo", DbType="VarChar(50)")]
		public string Mytwo
		{
			get
			{
				return this._Mytwo;
			}
			set
			{
				if ((this._Mytwo != value))
				{
					this.OnMytwoChanging(value);
					this.SendPropertyChanging();
					this._Mytwo = value;
					this.SendPropertyChanged("Mytwo");
					this.OnMytwoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mythree", DbType="VarChar(50)")]
		public string Mythree
		{
			get
			{
				return this._Mythree;
			}
			set
			{
				if ((this._Mythree != value))
				{
					this.OnMythreeChanging(value);
					this.SendPropertyChanging();
					this._Mythree = value;
					this.SendPropertyChanged("Mythree");
					this.OnMythreeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
